name: Project Management CI/CD

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    defaults:
      run:
        working-directory: ./
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
      BETTER_AUTH_URL: ${{ secrets.BETTER_AUTH_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.1.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash

      - name: Install dependencies
        run: bun install

      - name: Run ESLint
        run: bun run lint

      - name: Run Prettier
        run: bun run format:check

      # - name: Run Tests
      #   run: bun run test

      - name: Build the Project
        run: bun run build

      # - name: Deploy to Vercel
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      #   run: |
      #     npm install -g vercel
      #     vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --confirm
      #   env:
      #     VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      #     VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      # - name: Notify on Failure
      #   if: failure()
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       github.rest.issues.createComment({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         body: '🚨 CI/CD pipeline failed! Check the workflow logs for details.'
      #       })
